version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_project_container
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: poetry run python main.py
